spring:
  application:
    name: MicroService1EurekaClient
server:
  port: 8085
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
      